services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started  # este es el default (como si fuera solo "- redis")


  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASS}
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U ${POSTGRES_RESTRICTED_USER} -d ${POSTGRES_DB} -c '\\q'"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  pgdata: